### ISSUE TITLE
Is this stable?

### ISSUE THREAD

**Issue by nmn** [lodash/lodash-fp#1]
Or should I say, is this really unstable? 0.1.0 suggests its unstable, but it looks pretty stable.

**Comment by jdalton** [comment]
There isn't a lot of [moving parts](https://github.com/lodash/lodash-fp/blob/master/index.js) as it's 90% hash mapping but I didn't want to release it as stable 1.0 until devs had a chance to kick it around and supply feedback.

**Comment by nmn** [comment]
Thanks. I'll be one of those devs kicking it around in that case!

**Comment by jdalton** [comment]
Awesome, thanks!
