### ISSUE TITLE
reduce not providing all four arguments to iteratee function

### ISSUE THREAD

**Issue by miangraham** [lodash/lodash-fp#10]
Really loving lodash-fp! Tonight I'm trying to use it with reduce for the first time and running into an issue. Either I'm missing the correct usage here or there's a problem with the way the iteratee function is getting wrapped. In short, when reducing an object, the iteratee method is only being invoked with two arguments instead of four, so I can't get at the key corresponding to the value I'm provided.

Here's my minimal test code:

```javascript
'use strict';
var _ = require('lodash');
var fp = require('lodash-fp');

var stuff = { foo: 'bar' };

function noisyIdentity(result, value, key) {
  console.dir(arguments);
  result[key] = value;
  return result;
}

console.log('lodash reduce');
console.dir(_.reduce(stuff, noisyIdentity, {}));

console.log('lodash-fp reduce');
console.dir(fp.reduce(noisyIdentity, {})(stuff));

// Output:
// lodash reduce
// { '0': {}, '1': 'bar', '2': 'foo', '3': { foo: 'bar' } }
// { foo: 'bar' }
// lodash-fp reduce
// { '0': {}, '1': 'bar' }
// { undefined: 'bar' }
```

From what I can tell, baseFor has what it needs and is invoking iteratee with the key and value, but on reaching the body of noisyIdentity key is undefined--only two arguments are present rather than the standard four. It smells like the function has been wrapped with ary(2) or similar. Am I missing something? Thoughts appreciated!

**Comment by jdalton** [comment]
This is by design for lodash-fp. Capping the arguments provided helps with composition. So with `reduce` the params are capped to the `accumulator` and the current `value`. The chaining syntax would allow for the traditional 4 param lodash usage.

**Comment by miangraham** [comment]
Got it, thanks much for the info!
