### ISSUE TITLE
`pull` does not take multiple arguments

### ISSUE THREAD

**Issue by menelaos** [lodash/lodash-fp#13]
As `lodash`'s `pull` method is polyvariadic, I expected the following to work:

```javascript
_.pull(3, [1,2,3,4,5]);    // Works as expected
_.pull(3, 4, [1,2,3,4,5]); // Returns 4
```

I don't know how feasible it is to implement optional parameters in `lodash-fp`.

It might just be a documentation issue, when `lodash-fp`'s `pull` is intended to be only used with two arguments.

**Comment by jdalton** [comment]
fp-style doesn't really work well with variable arg signatures. This looks like something to compose with `_.each`.

If there's demand I'll add a version that accepts an array of values to pull.
