### ISSUE TITLE
Allow require of specified method

### ISSUE THREAD

**Issue by iam4x** [lodash/lodash-fp#14]
Like with main lodash, you can achieve this:

```javascript
// or a method (great for smaller builds with browserify/webpack)
var chunk = require('lodash/array/chunk');
```

Result: much smaller build

**Comment by thejameskyle** [comment]
@jdalton did you mean to tag this as wontfix?

**Comment by jdalton** [comment]
> did you mean to tag this as wontfix?

Yep, lodash-fp has the `require('lodash-fp/convert')` module that will be used to fp-ize modularized packages. It's not 100% ready for prime time but is used to fp-ize `lodash-compat` at the moment.

The idea is that you can pass it a method name or lodash instance to transform it.
```js
var convert = require('lodash-fp/convert'),
      map = convert('map', require('lodash.map'));
```
