### ISSUE TITLE
assign ignores some arguments

### ISSUE THREAD

**Issue by jakubholynet** [lodash/lodash-fp#16]
This ignores the last argument for some reason:
```js
_.assign({}, {a:1}, {b:2}); // expected: {a:1, b:2} (where the input b:2 object is modified)
// => { a: 1 }
```
However this works:
```js
_.assign({a:1}, {b:2}, {}); // => {a:1, b:2} as expected
// => { b: 2, a: 1 }
```

I suppose that either I misunderstand something seriously or that this is a bug. Thank you!

**Comment by jdalton** [comment]
Hi @jakubholynet! As mentioned [here](https://github.com/lodash/lodash/issues/1343) variadic methods don't fare well with this style which is why `_.assign` is capped to two params. You can always leverage composition of `_.reduce` + `_.assign` to get what you want.
