### ISSUE TITLE
Question: _.map iteratee not called with expected 3 args

### ISSUE THREAD

**Issue by JamieDixon** [lodash/lodash-fp#18]
Hi guys,

In non-fp lodash the iteratee called during `_.map` is passed 3 arguments: `(value, index|key, collection)` ref https://lodash.com/docs#map

In lodash-fp the iteratee only seems to be called with 1 argument, that being the `value`. Is this intentional or have I missed something?

Cheers.

**Comment by jdalton** [comment]
Hi @JamieDixon!

This is intentional for lodash-fp. Function composition doesn't favor optional params. Many functions you'd compose don't expect 3 arguments and that can cause issues. Related to #5 and #17.
