### ISSUE TITLE
Random

### ISSUE THREAD

**Issue by peterorum** [lodash/lodash-fp#2]
Great to see this module.

`_.random` seems to also have its args reversed
```js
_.random(0, 2) always gives 1
_.random(2, 0) gives 0, 1 or 2.
```
Is this expected?

**Comment by jdalton** [comment]
We could treat it like `_.range` and not flip its args.

**Comment by peterorum** [comment]
I would say so. For me, it's the max arg that would vary, and so perhaps should be last anyway. (e.g. _.random(0, array.length - 1)

**Comment by jdalton** [comment]
Sounds good to me. I'll patch tonight and bump.

**Comment by jdalton** [comment]
I read your [post over lodash-fp](http://codeindeed.com/post/109642878860/converting-to-lodash-fp). Currently the `lodash-fp` flavor of  [_.mixin](https://lodash.com/docs#mixin) supports [one argument](https://github.com/lodash/lodash-fp/blob/0.2.0/index.js#L26-L28). As you know fp style doesn't favor optional params so some cuts on optional params were done. In other areas we added alternative methods to accommodate cut params. For example [_.maxBy, _.minBy, _.uniqBy](https://github.com/lodash/lodash-fp/blob/0.2.0/index.js#L45-L49). As to the popularity I think it's way too soon to pass judgement on it. lodash has been out for nearly 3 years while lodash-fp has been out less than a week.

**Comment by peterorum** [comment]
Thanks. I was incorrectly using mixin like extend, and have updated the post.

Cheers,
Peter

**Comment by jdalton** [comment]
You note that some functions need their arguments reversed "unexpectedly, so be careful". Do you have an example of one that caused confusion?

**Comment by peterorum** [comment]
Not at the moment. Just mixin, which I was using wrongly anyway. And random, which was changed. Perhaps that will be all. I'll see as I use it more.

**Comment by jdalton** [comment]
> Not at the moment

Could you amend the post then?

**Comment by peterorum** [comment]
Sure. Done.
