### ISSUE TITLE
Dist shouldn't bundle lodash

### ISSUE THREAD

**Issue by megawac** [lodash/lodash-fp#21]
I think bundling `lodash` in the `dist/` files kinda defeats the purpose of this library. It would be better to just expect lodash to be defined, either by CJS, AMD, or a global variable.

**Comment by jdalton** [comment]
The purpose of the bower package is to get lodash-fp easily for the browser. The fact that underneath it's just lodash is an implementation detail.

Is there an easy way to accomplish this (a webpack option?).

**Comment by megawac** [comment]
Probably, I've never used webpack. It's easy enough to accomplish with `browserify` and `--exclude`

**Comment by megawac** [comment]
Related? https://github.com/webpack/webpack/issues/603

**Comment by jdalton** [comment]
Thanks for the references.

At the moment for the bower dist I've published the workflow others were using. While having one file nixes the advantages of modules it does simplify consumption (a single file, no module loaders or config).

For now I think we'll keep it simple.
