### ISSUE TITLE
_.throttle problems

### ISSUE THREAD

**Issue by Tuch** [lodash/lodash-fp#22]
Hi, how work with throttle method?

in original implementation its work.
```
_.throttle(function () {
    console.log(1)
}, 2000, {trailing: false})
```
i try something like this:
```
_.throttle({trailing: false}, function () {
     console.log(1)
})
```
its work, but i need third ‘2000’ param..
```
.throttle({trailing: false}, 2000, function () {
console.log(1)
})
```
and
```
.throttle(2000, {trailing: false}, function () {
console.log(1)
})
```

mb do something like this?
https://github.com/lodash/lodash-fp/compare/master...Tuch:experemental/with-throttle-fun

**Comment by jdalton** [comment]
At the moment lodash-fp's `_.throttle` doesn't accept an options argument. I was waiting for someone to request it.

Have a name suggestion? `_.throttleWithOptions` is kind of long.

**Comment by Tuch** [comment]
throttleWop :)

**Comment by jdalton** [comment]
Not touching that one. Maybe `WithOptions` isn't so bad. It could be applied to any method that accepts options. I'll kick it around tonight.
