### ISSUE TITLE
Create non-side effecting equivalents for lodash functions

### ISSUE THREAD

**Issue by khronnuz** [lodash/lodash-fp#25]
For proper functional programming, functions should not mutate in place. To overcome this when working with lodash I need to do something like

    var c7 = _.set(_.assign({}, ab), 'b.c', 17)`

**Comment by jdalton** [comment]
I plan on tackling this soon for `assign`, `defaults`, `extend`, I'll throw `set` on the list too. Feel free to add more that I should fix.

**Comment by AdamBrodzinski** [comment]
+1 this would be really big. This is one thing that has me on the edge with this and RamdaJS.

Thanks for all the hard work on lo-dash BTW! :beers:

**Comment by jdalton** [comment]
Patched https://github.com/lodash/lodash-fp/commit/69fb8e1d11bdfefc19cb38c31f1dc6ac94ecd87b.
