### ISSUE TITLE
Make original lodash accessible from lodash-fp or provide a factory to bower that takes lodash as a parameter

### ISSUE THREAD

**Issue by daedalus28** [lodash/lodash-fp#26]
I want to put this in production, but lodash is already present I can't justify the extra page weight from loading lodash twice.

This was brought up [before](https://github.com/lodash/lodash-fp/issues/21), but my suggesion is a bit different. Please either expose the bundled lodash (so I can just use this lib and reference the unmodified lodash for the legacy stuff), or provide a small factory in the bower repo that takes lodash as a parameter (but does not bundle lodash).

**Comment by jdalton** [comment]
Yep, I'll likely expose the `convert` module.

**Comment by daedalus28** [comment]
The current convert module requires in individual lodash modules, so I just want to be sure your intention is to handle the case where all of lodash is loaded in a browser scenario - in my case with AMD, but it should work with or without a module loader. I would imagine convert optionally taking in a lodash parameter. Is that your current line of thinking?

**Comment by jdalton** [comment]
Cool, with a little tweaking the `convert` method will bundle to 1.78 kB gzipped.

**Comment by jdalton** [comment]
Patched https://github.com/lodash/lodash-fp/commit/e0fc551d9ad0cd7f8a577e99e161e66d03244ef9.
