### ISSUE TITLE
Should extend have an arity of 2?

### ISSUE THREAD

**Issue by jgrund** [lodash/lodash-fp#3]
Thanks for making this. A typical pattern I use is:

`_.extend({}, {foo: 'bar'}, {bar: 'baz'})`

which pushes properties into the empty object and doesn't mutate any intermediary arguments.

Now that `_.extend` seems to have a fixed arity of 2, this no longer seems possible.

Is there a way to emulate this same behavior using lodash-fp?

If not, is there a way to have certain previously variadic methods still be so? I can see other cases where variadicness or user-defined arity could be useful.

**Comment by jdalton** [comment]
There's a couple of workarounds.

One nest the extend calls:
```js
_.extend({}, _.extend({foo: 'bar'}, {bar: 'baz'}))
```

or use the chaining API:

```js
_({}).extend({foo: 'bar'}, {bar: 'baz'}).value();
// => {foo: "bar", bar: "baz"}
```

The more functional style with composition doesn't favor optional/variadic params.
