### ISSUE TITLE
what's the signature for get()?

### ISSUE THREAD

**Issue by slifin** [lodash/lodash-fp#33]
I'm using the get() function 

I understand the data has been moved to the end so this works: 

    var object = { 'a': [{ 'b': { 'c': 3 } }] };
    alert(_.get('a[0].b.c',object));

but how do I add a default I've tried adding the default as the first, second and third parameters but none seem to work

**Comment by jdalton** [comment]
The `defaultValue` param is not supported in the lodash-fp flavor as optional params aren't supported in the fp- style. I could add it as something like a `_.getOr` or something. Do you have a naming preference?
