### ISSUE TITLE
What happened to _.compose?

### ISSUE THREAD

**Issue by DudeNamedBen** [lodash/lodash-fp#37]
I updated the library to the newest release and _.compose seems to be missing.
I checked the documentation of lodash and it still lists _.compose as an alias for flowRight.
Is this a bug or has the alias been removed?

JSfiddle containing the latest version to showcase the problem:
http://jsfiddle.net/rkm9n72g/

**Comment by jdalton** [comment]
Hi @DudeNamedBen! Make sure you're using a stable tagged release and not the edge master (unstable unreleased) code.
