### ISSUE TITLE
uniqueId has arity of 2

### ISSUE THREAD

**Issue by ritcoder** [lodash/lodash-fp#38]
unqueId requires two arguments to produce a result. I was expecting one. Is it supposed to be so as I do not see what the first argument is for

    import {uniqueId} from 'lodash-fp';
    const id = uniqueId('a','b'); //result is b1
    const wasExpected = uniqueId("b"); //this returns the wrapper() function

**Comment by jdalton** [comment]
Thanks for the heads up!
