### ISSUE TITLE
map indexed doesn't seem to work?

### ISSUE THREAD

**Issue by vshesh** [lodash/lodash-fp#40]
I'm not sure if this is how it is supposed to be, but in regular lodash the iteratee for map can take up to 3 args. On the latest bower install (0.10.2) of lodash-fp, map only seems happy with one argument - 

```js
_.map(function(x,i) { return i}, [1,2,3])
[undefined, undefined, undefined]
```
I traced this to a problem in the way that the iteratee is being called - the problem is on line 2077 where it says `argCount = argCount > 2 ? (argCount - 2) : 1;` - this is a problem because the original argCount was 3, and that is what it is supposed to be. This line shrinks it down to 1, i.e. only the element. 
If I remove this line, everything seems to work as expected (map works properly and none of the other functions I've used seem broken) - is the 1-arg only behavior expected? If not, is this the correct fix?

**Comment by jdalton** [comment]
Hi @vshesh! This is by design to aid functional composition. The `index` and `array` params have been known to cause unintended side effects to iteratees like:
```js
['6', '08', '10'].map(parseInt)
// => [6, NaN, 2]
```
