### ISSUE TITLE
zip is backwards?

### ISSUE THREAD

**Issue by vshesh** [lodash/lodash-fp#42]
Again, my apologies if this is The Way It Is Supposed To Be but I found this strange (latest bower install)

```js
_.zip([1,2,3],[4,5,6]) 
=> [[4,1],[5,2],[6,3]]
```

And then of course, it's not multi-arity so it only works for two arrays at at a time (meaning general zip should be written `function zipall(){_.reduce(_.zip, arguments[0], arguments.slice(1))}`), but I assume that's what you were going for given my previous question.

Still, why backwards?

**Comment by jdalton** [comment]
@vshesh Thanks for hammering on this. You're helping get things settled for our 1.0 release :D

**Comment by jdalton** [comment]
Fixed via https://github.com/lodash/lodash/commit/f16e0c46d65703e920bc35d173ea0ffec4ad459a.
