### ISSUE TITLE
_.merge is backwards 

### ISSUE THREAD

**Issue by vshesh** [lodash/lodash-fp#43]
Just tried to use merge, and got this behavior:

```js
_.merge({x:1},{x:2})
=> {x:1}
_.merge({x:3},{x:2})
=> {x:3}
x= {x:1}
_.merge({x:2},x}
=> {x:2}
x
=> {x:2}
```

I think it's actually trying to work in reverse - pushes the first object onto the second and so on.
I suppose you *could* make an argument that this is how it's supposed to be, since `_.partial(_.merge, {x:2}))` becomes a function that replaces the property x on any object with the value 2 without modifying it's original argument (the `{x:2}` in this case), but it definitely doesn't match the behavior of [other](http://clojuredocs.org/clojure.core/merge) [functional](https://toolz.readthedocs.org/en/latest/api.html#toolz.dicttoolz.merge) [implementations](http://ramdajs.com/0.18.0/docs/#merge). Plus, I'm pretty sure that's what `assign` is for.

And a side note that `extend` from underscore matches `lodash.merge` not `lodash.extend` - not an actual issue, but I did get confused for a while when figuring this out.

**Comment by vshesh** [comment]
nvm _.merge and _.assign are supposed to be opposites.

**Comment by vshesh** [comment]
this breaks my expectations from underscore http://underscorejs.org/#extend

**Comment by jdalton** [comment]
For lodash-fp methods many arguments are reversed/flipped to allow easier composition. This goes in to #17. I'll be sure to document these for our next release.
