### ISSUE TITLE
zipObject works properly in Node, but gives incorrect results in browsers.

### ISSUE THREAD

**Issue by qmulos-michael** [lodash/lodash-fp#44]
Using the following test code with lodash-fp:
```
var result = _.zipObject(["a", "b", "c"], [1, 2, 3]);
console.log(result);
```

Node produces the correct results:
```{ a: 1, b: 2, c: 3 }```

However, both Firefox and Chrome browsers produce the following incorrect results:
```{a: undefined, b: undefined, c: undefined}```

**Comment by jdalton** [comment]
This is fixed in edge master branch of lodash.
