### ISSUE TITLE
Missing parameters in _.partition predicate.

### ISSUE THREAD

**Issue by lewie9021** [lodash/lodash-fp#45]
I'm trying to split up an array of values using a filter function (_.partition). However, I want to split by the index of the current iteration. In the main `lodash` module, the predicate function is passed the value, index, and collection respectively. When I use lodash-fp, I only seem to get the value, nothing else. I'm still rather new to `lodash` and even more so `lodash-fp`, I hope it's just something I'm doing wrong

Library versions:
- **lodash** (3.10.1)
- **lodash-fp** (0.10.2)

```javascript
var _ = require("lodash-fp")

var data = [1, 2, 3]
var result = _.partition(function(x, i) { return i % 2; }, data);
console.log(result) // [[], [1, 2, 3]]
```

```javascript
var _ = require("lodash")

var data = [1, 2, 3]
var result = _.partition(data, function(x, i) { return i % 2; });
console.log(result) // [[2], [1, 3]]
```

**Comment by jdalton** [comment]
This is by design as functional composition favors single param `iteratees`.
