### ISSUE TITLE
Enhancement: register with a lodash instance (enables non compat)

### ISSUE THREAD

**Issue by megawac** [lodash/lodash-fp#6]
Example

```js
import _ from 'lodash';
let σ = require('lodash-fp').register(_);
```

`register` would still of course use `runInContext` but would allow users to register it with the modern build

Hell, if underscore ever gets `runInContext` (https://github.com/jashkenas/underscore/issues/2001) and a bunch of other enhancements it may even work

**Comment by jdalton** [comment]
> `register` would still of course use `runInContext` but would allow users to register it with the modern build

lodash-compat would still be a dep via the package.json though. Not sure if the modern build is a big enough draw it boils down to a kb or two.

>  I'm not maintaining that!

What's that mean?

**Comment by megawac** [comment]
> lodash-compat would still be a dep via the package.json though. Not sure if the modern build is a big enough draw it boils down to a kb or two.

Yeah, I'm suggesting that it shouldn't be a dep. Devs should either register it themselves or `require('lodash-fp-compat')` or what not

**Comment by jdalton** [comment]
Ah, I could abstract the `lodash-fp` mixin into `lodash-fp-mixin` or something and use it for `lodash-fp` and others. This would allow it to be applied to custom lodash builds and transform them too (works well with browserify/webpack).

**Comment by jdalton** [comment]
lodash-fpify. lodash-fplugin, ...

**Comment by jdalton** [comment]
I could see this easily working at least partially for underscore too (minus the chaining part).

**Comment by jdalton** [comment]
Maybe call it `fpify`. Bikeshed name time.

**Comment by megawac** [comment]
I think `lodash-fp-mixin` is appropriate for what its doing and in line with other names

**Comment by jdalton** [comment]
Rock. Possible usage:
```js
var mixin = require('lodash-fp-mixin');

var _ = mixin(require('underscore'))

// maybe by id
var each = mixin('each', require('lodash.foreach'));

// or 
_ = mixin({ 'each': require('lodash/collection/each') });
```

**Comment by megawac** [comment]
I kind of prefer the idea of having the mixin call run in context myself
and returning the new instance

On Wed, Feb 11, 2015 at 7:51 PM, John-David Dalton <notifications@github.com

**Comment by jdalton** [comment]
I rather keep it simple so it works with lodash or others. You can always pass `mixin(_.runInContext())`.
We would have that as a doc example.

**Comment by megawac** [comment]
Yeah, fair enough!

**Comment by jdalton** [comment]
Just working on this. It won't work with Underscore because it references `_.xyz` internally so when methods are flipped they still attempt to use them the old way causing stuff to blow up.

**Comment by jdalton** [comment]
Part way there with https://github.com/lodash/lodash-fp/commit/84c807715c339f39755fc7bf7fa70a7b20557163

**Comment by jdalton** [comment]
Instead of a separate package I'm going to rename the internal `mixin.js` to `ify.js` so devs can use:
```js
var ify =require('lodash-fp/ify');
```
