### ISSUE TITLE
Add bower support.

### ISSUE THREAD

**Issue by afcondon** [lodash/lodash-fp#7]
I'd love to be able to pull vanilla lodash from bower_components in a work project and replace with lodash-fp.

**Comment by jdalton** [comment]
Yep there are plans for that.

**Comment by afcondon** [comment]
Great! Thanks a lot.

**Comment by jdalton** [comment]
I haven't decided if I want to have a `dist/` folder or a branch for it.
The plan is to have it browserified/minified. Though I could see the benefit of just using the `convert.js` to convert an existing lodash instance into -fp.

**Comment by daedalus28** [comment]
Have you considered having a `dist/` folder with both a bundled standalone build and one that takes lodash as a parameter? In my project, we are already using lodash and would love to start using this, but can't switch over all at once. Loading lodash twice would be unfortunate.

**Comment by I-Ivanov** [comment]
Hi, we are planning of using lodash-fp in a full mean stack project. Since there is no bower support is there any possible way to use the -fp version in the browser.

**Comment by avimar** [comment]
+1 I use lodash-fp in my node.js scripts and I'd like to include it in my client-side code, too.

**Comment by I-Ivanov** [comment]
Ok we solved it using browserify which can be later combined with gulp to ensure that u always have consitency between versions.
http://browserify.org/#install
This is hopefully temporary solution till there is bower support.

**Comment by daedalus28** [comment]
Browserify doesn't fully solve the use case of using this on the client - if you're already using requirejs (like we are), it won't work.

**Comment by jdalton** [comment]
You should be able to browserify in a way that won't affect amd loaders.

**Comment by daedalus28** [comment]
@jdalton while we may be able to make it available as a global that gets loaded before requirejs does, I'm not aware of any way to load a browserified module through requirejs in the same way we're currently loading lodash. If you know of something, I'd greatly appreciate being pointed in the right direction.

**Comment by jdalton** [comment]
@daedalus28 I can't repro. Try:
```bash
browserify . -s _ -o bundle.js
```

**Comment by jdalton** [comment]
Closing by way of https://github.com/lodash/lodash-fp/commit/706d333feb8a01d8d6dec4d8289838fdcf40f231. I'll move the tag up to catch it.

**Comment by avimar** [comment]
Can't install lodash-fp...
```
bower install lodash
bower not-cached    git://github.com/lodash/lodash.git#*
bower resolve       git://github.com/lodash/lodash.git#*
bower download      https://github.com/lodash/lodash/archive/3.10.1.tar.gz

bower install lodash-fp
bower ENOTFOUND     Package lodash-fp not found

**Comment by jdalton** [comment]
Yah, I still need to publish it.

**Comment by quadroid** [comment]
Please update npm package and readme.
Thanks!

**Comment by jdalton** [comment]
Updated, registered, and tagged.

**Comment by quadroid** [comment]
npm package v 0.10.2 still doesn't have dist folder :(

**Comment by jdalton** [comment]
Works for me.

**Comment by jdalton** [comment]
The npm package wouldn't have the dist. If you want client side use bower. If you want npm to client side then use the same setup I'm doing to webpack bundle it.
