### ISSUE TITLE
Documentation - e.g max changed to maxBy

### ISSUE THREAD

**Issue by avimar** [lodash/lodash-fp#9]
It was a bit of a gotcha to see my .max('key') didn't work until I changed it to maxBy after checking convert.js

Where are the docs for this..?

**Comment by jdalton** [comment]
They'll be added to the next bump. Because FP-style doesn't work well with optional params separate methods are created to handle the variation. They are `_.maxBy`, `_.minBy`, `_.uniqBy` and `_.curryN`.
